name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre.
  pull_request:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre.

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Paso 3: Hacer caché de las dependencias de SonarCloud
      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*', '**/*.java', '**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

